apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "net-exporter.fullname" . }}
  labels:
    {{- include "net-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  resourceNames:
  - {{ include "net-exporter.fullname" . }}
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - kube-system
  verbs:
  - get
  - update
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "net-exporter.fullname" . }}
  verbs:
  - "use"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "net-exporter.fullname" . }}
  labels:
    {{- include "net-exporter.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "net-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "net-exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
