apiVersion: v1
kind: Service
metadata:
  name: {{ include "net-exporter.fullname" . }}
  labels:
    {{- include "net-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "net-exporter.selectorLabels" . | nindent 4 }}
