apiVersion: v1
appVersion: 1.2.1
description: |
  net-exporter is a Prometheus exporter for exposing network information in Kubernetes clusters. It is packaged as a Helm chart.

  net-exporter runs as a Kubernetes Daemonset. This is to allow for intra-pod network calls, to determine network latency.
name: net-exporter
version: 0.1.0
home: https://github.com/giantswarm/net-exporter
maintainers:
- name: max-rocket-internet
  email: no-reply@deliveryhero.com
